add mathjax support
xzhih/hexo-theme-casper pull request #2
Opened 2018-03-30 10:12 UTC by batkiz

2018-04-01 08:34 UTC, batkiz commented
由于是打算随意改改自己用的，所以没多考虑这个😅

2018-04-01 09:56 UTC, xzhih commented
原来是这样啊，那你可以随意爆改了

2018-04-01 14:30 UTC, batkiz commented
@xzhih 
我太菜了，魔改这个要耗很大精力😩，不打算继续搞了😶。
可以的话合并一下我代码到 `5465f5b6436365c0bddb793837bc384a120a3f6b`为止的commit吧。改的东西都在commits信息里写了。

顺带反馈个Bug：about页面不能正常渲染，应该是因为用了`index.swig`的原因。

2018-04-01 15:24 UTC, xzhih commented
about页我之前忘记弄了，多谢提醒

mathjax的参数设置建议放到config里可以让人自定义

copyright的部分我觉得没必要写的一长串的，有个意思就行

目前我就先合并social icon那里吧

2018-04-01 15:26 UTC, xzhih reviewed
add some social links icons

2018-04-01 15:30 UTC, xzhih requested changes
add some social links icons

2018-04-01 15:31 UTC, xzhih approved these changes

2018-04-01 15:40 UTC, xzhih approved these changes

2018-04-01 16:38 UTC, merged

2019-06-20 06:34 UTC, woriazzc commented
你好，我用了mathjax后localhost能加载，但发布到网页之后就不行了。 @batkiz
少了cdn的js。请问怎么解决呢？
![捕获1](https://user-images.githubusercontent.com/44539042/59826231-79272080-9368-11e9-85f4-a47919f0c31b.PNG)
![捕获](https://user-images.githubusercontent.com/44539042/59826233-7af0e400-9368-11e9-953d-c263ba88f90c.PNG)